name: Defibrillate

on:
  schedule:
    - cron:  '30 * * * *'
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: |
        gh workflow disable -R codefodder/HackerNews-DIYgest 56662080
        sleep 10
        gh workflow enable -R codefodder/HackerNews-DIYgest 56662080
