name: Flatline & Resuscitate

on:
  schedule:
    - cron:  '30 0 * * *'
    
  workflow_dispatch:
  
env:
  GH_TOKEN: ${{ github.token }}
  
jobs:
  flatline_and_resuscitate:
    runs-on: ubuntu-latest
    steps:
    - name: Flatline & Resuscitate
      run: |
        gh workflow enable -R codefodder/HackerNews-DIYgest 56662080
    - name: Lazarus
      run: |
        gh workflow enable -R codefodder/HackerNews-DIYgest 56662080
