name: Hacker News DIYgest Hourly Scrape

env:
  TARGET_HOUR: "08" # Bangkok Time
  TARGET_HOUR_UTC: 1 # for cron

on:
  workflow_dispatch:
    inputs:
      send-email:
        description: Force send email on this run?
        default: "no thanks"
        type: choice
        options:
          - "force"
          - "no thanks"

  schedule:
    - cron: "0 * * * *"
    - cron: "*/15 ${{ env.TARGET_HOUR_UTC}} * * *"

jobs:
  Hacker-News-DIYgest-Hourly-Scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch database and sent.yml
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
           # create an empty sent file...
           echo "sent: never" > sent.yml

           # fetch the database and yml from artifact.zip
           gh auth login --with-token <<<"$ACCESS_TOKEN"
           asset=$(gh api /repos/codefodder/hacker-news-digest/actions/artifacts --jq ".artifacts[0] .archive_download_url")
           curl -L -s -o artifact.zip "$asset" \
           -H "Accept: application/vnd.github.v3+json" \
           -H "Authorization: Bearer $ACCESS_TOKEN"
           unzip -o artifact.zip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y markdown

      - name: Scrape
        run: bin/hn-hourly-scrape.py

      - name: Review Current Top Stories
        run: |
          sqlite3 hn.db < stories.sql >> "$GITHUB_STEP_SUMMARY"

      - name: Compose email
        run: bin/compose-email.sh

      - name: Read sent.yml
        id: read_yaml
        uses: actions-tools/yaml-outputs@v2
        with:
          file-path: 'sent.yml'

      - name: Decide if email is sent
        run: |
          should_send_email=false

          hour_now=$(TZ=Asia/Bangkok date +%H)
          today="$(TZ=Asia/Bangkok date +%Y%m%d)"
          last_sent="${{ steps.read_yaml.outputs.sent }}"
          if [[ "$today" != "$last_sent" && "$TARGET_HOUR" == "$hour_now" ]]; then
            echo "SEND_MAIL=true" >> "$GITHUB_ENV"
          fi

          <<DEBUG_EMAIL_SCHEDULE >> "$GITHUB_STEP_SUMMARY"

          Email schedule info

          - Last Sent: ${last_sent}
          - Today: ${today}
          - Target Hour: ${TARGET_HOUR}
          - Target Hour (UTC): ${TARGET_HOUR_UTC}
          - Current Hour: [${hour_now}]
          - Force Email: ${{ inputs.send-email  }}

          DEBUG_EMAIL_SCHEDULE

      - name: Email HackerNews DIYgest
        id: sending_email
        if: |
          ${{ env.SEND_MAIL == 'true' || inputs.send-email == 'force' }}
        uses: dawidd6/action-send-mail@v3
        with:
          subject: ${{ env.SUBJECT_LINE }}
          from: HackerNews DIYgest
          to: ${{secrets.GMAIL_USER}}
          username: ${{secrets.GMAIL_USER}}
          password: ${{secrets.GM_APPWRD}}
          body: file://stories.md # plaintext
          html_body: file://digest.html
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          ignore_cert: true
          priority: high
          
      - name: Confirm sent
        if: ${{ success() }}
        run: |
          today=$(TZ=Asia/Bangkok date +%Y%m%d)
          echo "sent: $today" > sent.yml

      - name: Upload database artifact
        uses: actions/upload-artifact@v2
        with:
          name: hackernews-database
          path: |
            hn.db
            sent.yml
