name: Hacker News DIYgest Hourly Scrape

on:
  workflow_dispatch:
    inputs:
      send-email:
        description: Force send email on this run?
        default: no
        type: choice
        options:
          - yes
          - no

  schedule:
    - cron: "0 * * * *"
    - cron: "*/15 12 * * *" # Asia/Bangkok 11 == 19:00-19:59am (UTC+07:00) (TESTING)

jobs:
  Hacker-News-DIYgest-Hourly-Scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch database and sent.yml
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
           # create an empty sent file...
           echo "sent: never" > sent.yml

           # fetch the database and yml from artifact.zip
           gh auth login --with-token <<<"$ACCESS_TOKEN"
           asset=$(gh api /repos/codefodder/hacker-news-digest/actions/artifacts --jq ".artifacts[0] .archive_download_url")
           curl -L -s -o artifact.zip "$asset" \
           -H "Accept: application/vnd.github.v3+json" \
           -H "Authorization: Bearer $ACCESS_TOKEN"
           unzip -o artifact.zip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y markdown

      - name: Scrape
        run: bin/hn-hourly-scrape.py

      - name: Review Current Top Stories
        run: |
          sqlite3 hn.db < stories.sql >> "$GITHUB_STEP_SUMMARY"

      - name: Compose email
        run: bin/compose-email.sh

      - name: Read sent.yml
        id: read_yaml
        uses: actions-tools/yaml-outputs@v2
        with:
          file-path: 'sent.yml'

      # - name: Skip if email sent today
      #   run: |
      #     echo "## Sent last: $(cat sent.yml)" >> "$GITHUB_STEP_SUMMARY"
      #     today="$(TZ=Asia/Bangkok date +%Y%m%d)"
      #     if [[ "${{ steps.read_yaml.outputs.sent }}" == "$today" ]]; then
      #       echo "SEND_MAIL=false" >> "$GITHUB_ENV"
      #     fi

      - name: Email HackerNews DIYgest
        id: sending_email
        if: ${{ env.SEND_MAIL == true || inputs.send-email == 'yes' }}
        uses: dawidd6/action-send-mail@v3
        with:
          subject: ${{ env.SUBJECT_LINE }}
          from: HackerNews DIYgest
          to: ${{secrets.GMAIL_USER}}
          username: ${{secrets.GMAIL_USER}}
          password: ${{secrets.GM_APPWRD}}
          body: file://stories.md # plaintext
          html_body: file://digest.html
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          ignore_cert: true
          priority: high
          
      - name: Confirm sent
        if: ${{ success() }}
        run: |
          today=$(TZ=Asia/Bangkok date +%Y%m%d)
          echo "sent: $today" > sent.yml

      - name: Upload database artifact
        uses: actions/upload-artifact@v2
        with:
          name: hackernews-database
          path: |
            hn.db
            sent.yml
